config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :general_reports, except: %i[edit update]
  resources :reports, only: %i[index show]
  root 'general_reports#index'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/general_report.rb
# frozen_string_literal: true

class GeneralReport < ApplicationRecord
  has_many :reports, dependent: :destroy
  validates :data, presence: true
end

app/models/report.rb
# frozen_string_literal: true

class Report < ApplicationRecord
  validates :carrier, presence: true
  validates :tracking_number, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/general_reports_controller.rb
# frozen_string_literal: true

class GeneralReportsController < ApplicationController
  before_action :find_resource, only: %i[show destroy]

  def index
    @general_reports = GeneralReport.all
  end

  def show; end

  def new
    @general_report = GeneralReport.new
  end

  def create
    @general_report = GeneralReport.new(general_report_params)

    respond_to do |format|
      if @general_report.save
        OverweightReporter.call(@general_report)
        format.html { redirect_to @general_report, notice: t('flash.create.general_report.notice') }
        format.json { render :show, status: :created, location: @general_report }
      else
        format.html { render :new, alert: t('flash.create.general_report.alert') }
        format.json { render json: @general_report.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    respond_to do |format|
      if @general_report.destroy
        format.html { redirect_to general_reports_url, notice: t('flash.destroy.general_report.notice') }
        format.json { head :no_content }
      else
        format.html { redirect_to @general_report, alert: t('flash.destroy.general_report.alert') }
        format.json { render json: @general_report.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def find_resource
    @general_report = GeneralReport.find(params[:id])
  end

  def general_report_params
    { data: params[:general_report][:data] }
  end
end

app/controllers/reports_controller.rb
# frozen_string_literal: true

class ReportsController < ApplicationController
  def index
    @reports = Report.all
  end

  def show
    @report = Report.find(params[:id])
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/general_reports_helper.rb
# frozen_string_literal: true

module GeneralReportsHelper
end

app/helpers/reports_helper.rb
# frozen_string_literal: true

module ReportsHelper
end

app/views/general_reports/_form.html.erb
<%= form_with(model: general_report, local: true) do |f| %>
  <% if general_report.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(general_report.errors.count, "error") %> </h2>

      <ul>
        <% general_report.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <div class="control">
      <%= f.label :data %>
      <%= f.text_field :data, class: "input is-link"%>
    </div>
  </div>

  <div class="actions">
    <%= f.submit t('.create'), class: "button is-link"%>
  </div>
<% end %>

app/views/general_reports/_report.html.erb
<div class="card">
  <div class="card-content">
    <div class="media">
      <div class="media-left">
        <figure class="image  is-128x128">
          <%= image_tag "#{report.overweight.zero? ? 'box' : 'overweight'}.svg" %>
        </figure>
      </div>
      <div class="media-content">
        <div class="columns is-desktop">
          <div class="column">
            <p class="title is-6"><%=t('.platform_weight')%></p>
            <p class="subtitle is-6"><%=report.total_weight%></p>
         </div>
          <div class="column">
            <p class="title is-6"><%=t('.fedex_weight')%></p>
            <p class="subtitle is-6"><%=report.weight_fedex%></p>
          </div>
          <div class="column">
            <p class="title is-6"><%=t('.overweight')%></p>
            <p class="subtitle is-6 has-text-danger	"><%=report.overweight if report.overweight > 0%></p>
            <p class="subtitle is-6 has-text-danger	"><%=t('.platform_overweight') if report.overweight < 0%></p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/general_reports/index.html.erb
<section class="section">
  <div class="container">
    <p id="notice"><%= notice %></p>

    <h1><%=t('.general_reports')%></h1>

    <table class="table is-narrow table is-hoverable">
      <thead>
        <tr>
          <th><%=t('.data')%></th>
          <th colspan="2"></th>
        </tr>
      </thead>

      <tbody>
        <% @general_reports.each do |general_report| %>
          <tr>
            <td><%= general_report.data %></td>
            <td><%= link_to t('.show'), general_report, class: 'button is-link' %></td>
            <td><%= link_to t('.destroy'), general_report, method: :delete, class:'button is-danger', data: { confirm: t('.are_you_sure') } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <br>

    <%= link_to t('.new_general_report'), new_general_report_path, class: 'button is-link' %>
  </div>
</section>

app/views/general_reports/new.html.erb
<section class="section">
  <div class="container">
    <h1><%=t('.new_general_report')%></h1>

    <%= render 'form', general_report: @general_report %>

    <%= link_to t('.back'), general_reports_path %>
  </div>
</section>

app/views/general_reports/show.html.erb
<p id="notice"><%= notice %></p>

<section class="section">
  <div class="container">
    <h1><%= t(".report_of") %><%=l @general_report.created_at, format: :date%></h1>
    <%= render partial: 'report', collection: @general_report.reports %>
    <%= link_to t('.back'), general_reports_path %>
  </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OverweightPackages</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/reports/_report.html.erb
<td><%= report.tracking_number %></td>
<td><%= report.carrier %></td>
<td><%= report.total_weight %></td>
<td><%= report.weight_fedex %></td>
<td><%= report.overweight %></td>

app/views/reports/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Reports</h1>

<table>
  <thead>
    <tr>
      <th>Tracking number</th>
      <th>Carrier</th>
      <th>Length</th>
      <th>Width</th>
      <th>height</th>
      <th>weight</th>
      <th>Distance unit</th>
      <th>Mass unit</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <tr>
      <%= render partial: 'report', collection: @reports %>
    </tr>
  </tbody>
</table>

<br>

app/views/reports/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tracking number:</strong>
  <%= @report.tracking_number %>
</p>

<p>
  <strong>Carrier:</strong>
  <%= @report.carrier %>
</p>

<%= link_to 'Back', reports_path %>